### PR TITLE
Add the versions table to the README for quick access

### PR DESCRIPTION
**Pull request by agrare**
Maintain compatibility with chrisarcand/miqversion :)

Add the versions table to the README so people can quickly view it
without having to install the gem

This will have to be updated when the versions table is modified.

### CODE REVIEW

**Comment by agrare** [comment]
No credit needed I just wanted to be able to see the versions in the readme it's all yours

**Comment by NickLaMuro** [comment]
^ Done.

**Comment by simaishi** [comment]
We have CloudForms "3.1" and "4.1" twice each in the table!

**Comment by agrare** [comment]
Lol @simaishi is the only one that actually reviewed the content of the table

**Comment by agrare** [comment]
@NickLaMuro you want to fix that in your PR? I'm going to close this one.

**Pull request closed without merging**
